server:
  port: 8080
springdoc:
  api-docs:
    enabled: true
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5436/testdb
    username: user
    password: password
  liquibase:
    change-log: classpath:liquibase/master.xml
